spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ${DB_PASSWORD:password}
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:mydatabase}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:root}
  flyway:
    baseline-on-migrate: true
    password: ${DB_PASSWORD:password}
    schemas: irina_updater
    user: ${DB_USER:root}
