spring:
    profiles:
        active: prod
    security:
        user:
            password: ${IrinaBotUpdaterPassword}
    servlet:
        multipart:
            enabled: true
            max-file-size: 1024MB
            max-request-size: 1024MB
    sql:
        init:
            mode: always

    jpa:
        generate-ddl: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

irinabot:
    updater:
        location: ${IrinaBotUpdaterFolder}